name: Code Analysis

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    code_analysis:
        strategy:
            fail-fast: false
            matrix:
                php:
                    - "8.1"
                    - "8.2"
                    - "8.3"
                actions:
                    -
                        name: "PHPStan"
                        run: vendor/bin/phpstan

                    -
                        name: "PHPUnit"
                        run: vendor/bin/phpunit

        name: PHP${{ matrix.php }}:${{ matrix.actions.name }} 
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v4

            # see https://github.com/shivammathur/setup-php
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }})
                    coverage: none

            # composer install cache - https://github.com/ramsey/composer-install
            -   uses: "ramsey/composer-install@v2"

            -   run: ${{ matrix.actions.run }}
